version: '3.4'

services:
  mysql.db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ${FINAPI_DatabaseConfiguration__FinaApiDb__Database}
      MYSQL_USER: ${FINAPI_DatabaseConfiguration__FinaApiDb__UserId}
      MYSQL_PASSWORD: ${FINAPI_DatabaseConfiguration__FinaApiDb__Password}
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql
    restart: always
  finance.web.api:
    image: ${DOCKER_REGISTRY-}financewebapi
    build:
      context: .
      dockerfile: Finance.Web.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44349
      - FINAPI_DatabaseConfiguration__FinaApiDb__Database
      - FINAPI_DatabaseConfiguration__FinaApiDb__Password
      - FINAPI_DatabaseConfiguration__FinaApiDb__Port
      - FINAPI_DatabaseConfiguration__FinaApiDb__Server=mysql.db
      - FINAPI_DatabaseConfiguration__FinaApiDb__UserId
    ports:
      - 12345:80
      - 44319:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https
    depends_on:
      - mysql.db